In [15]:
# imports
import pandas as pd
import numpy as np

phenotype_file = 'pgen.1007217.s010.xlsx'

## Extract Phenotype data from yeast study

In [16]:
with pd.ExcelFile(phenotype_file) as xlsx:
    yeast_info = pd.read_excel(xlsx, "Column Information")
    yeast_pheno_data = pd.read_excel(xlsx, "DATA")

/opt/homebrew/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [17]:
yeast_pheno_data

,Strains,Niche,Location,SynH Final OD600,SynH Percent glucose consumed,HT Tolerance based on OD600,HT Tolerance based on glucose consumption,Number of SNPs compared to S288c (ref Strain),Percent pairwise genetic divergence,Percent of Heterozygous SNPs,Population based on PCA coordinates
0,273614N,Clinical,"Newcastle, UK",5.5000,50.000000,70.512821,61.313348,48534,0.401107,3,8
1,378604X,Clinical,"Newcastle, UK",0.3625,2.868391,3.091684,3.377585,46222,0.382000,3,8
2,BC187,Other Fermentation,"Napa Valley, USA",6.5600,69.178853,65.257399,70.055980,42617,0.352207,2,1
3,CBS7960,Industrial fermentation (sugar cane),"Sau Paulo, Brazil",6.5125,58.717660,67.139175,59.588245,47900,0.395868,3,1
4,CLIB324,Bakery,Vietnam,3.5750,30.033746,63.839286,56.576727,46951,0.388025,98,8
...,...,...,...,...,...,...,...,...,...,...,...
160,YPS163,Oak,"Pennsylvania, USA",7.6750,68.110236,75.152999,81.034201,61484,0.508132,2,3
161,YPS606,Natural Isolate,"Woodland, PA",6.9300,65.466817,63.753450,76.798901,60376,0.498975,3,3
162,YS2,Bakery,Australia,6.9500,66.704162,57.736241,80.138287,42187,0.348653,2,1
163,YS4,Bakery,The Netherlands,3.9625,50.899888,37.206573,54.243537,86918,0.718331,73,8
164,YS9,Bakery,Singapore,7.4875,75.084364,66.041896,80.370678,61764,0.510446,59,8

## Drop unwanted rows (only 4 columns for toxin tolerance)
### Also clean column names since GAPIT needs tab-delimited file

In [18]:
pheno_data = yeast_pheno_data.drop(columns=['Niche', 'Location'])
pheno_data = pheno_data.iloc[:,:5]
cleaned_columns = [col.replace(' ', '_') for col in pheno_data.columns]
pheno_data.columns = cleaned_columns
pheno_data

,Strains,SynH_Final_OD600,SynH_Percent_glucose_consumed,HT_Tolerance_based_on_OD600,HT_Tolerance_based_on_glucose_consumption
0,273614N,5.5000,50.000000,70.512821,61.313348
1,378604X,0.3625,2.868391,3.091684,3.377585
2,BC187,6.5600,69.178853,65.257399,70.055980
3,CBS7960,6.5125,58.717660,67.139175,59.588245
4,CLIB324,3.5750,30.033746,63.839286,56.576727
...,...,...,...,...,...
160,YPS163,7.6750,68.110236,75.152999,81.034201
161,YPS606,6.9300,65.466817,63.753450,76.798901
162,YS2,6.9500,66.704162,57.736241,80.138287
163,YS4,3.9625,50.899888,37.206573,54.243537
164,YS9,7.4875,75.084364,66.041896,80.370678

## Export to *tab-delimited* file!!

In [19]:
pheno_data.to_csv("pheno_data.tsv", sep='\t')